- name: Install nginx
  apt:
    name: 
      - nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Ensure nginx configuration is correct
  command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
- name: start nginx
  service:
    name: nginx
    state: started
  become: yes

- name: Deploy index.html template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes

